final Map<String, String> enUs = {
  'homeAppTitle':'NoobBlog',
  'postedOn':'Posted on',
  'language': 'Global',
  'scienceOnline':'ScienceOnline',
  'home': 'Home',
  'homeTitle':'About my blog',
  'homeSubTitle':'Blog building',
  'homeIntroduce':'Advice is welcome',
  'music':'Music',
  'nomalSea':'Sea',
  'nomalQiCai':'Colorful',
  'gradientRotate':'Dynamic Rotation',
  'gradientSea':'Dynamic Sea',
  'gradientQiCai':'Dynamic Colorful',
  'langZh' : '中文',
  'langEn' : 'ENGLISH',
  'theme': 'Theme',
  'text':'Text',
  'cao':'Cao',
  'xing':'Xing',
  'kai':'Kai',
  'personName':'Noob',
  'geocoor':'Distance',
  'lat':'Lat',
  'long':'Long',
  'location':'Map',
  'rain':'Rain',
  'sunny':'Sunny',
  'frontUntil':'until the weekend for',
  'backUntil':'days',
  'untilWeekend':'holiday!',
  'mondayFeel':'every day is a new beginning',
  'tuesdayFeel':'if you like it, stick to it',
  'wednesdayFeel':'regrets can be harder than failures',
  'thursdayFeel':'make small but daily progress',
  'fridayFeel':'as the last day',
  'weekendFeel':"work hard but don't forget to live",
  'article':'article',
  'label':'label',
  'personHome':'Person Home',
  'noLocation':'unable to get location information',
  'person':'Person',
  'flutter':'Flutter',
  'golang':'Go',
  'java':'Java',
  'personLabel':'person center',
  'flutterLabel':'flutter',
  'sciLabel':'scientific internet',
  'javaLabel':'java',
  'goLabel':'golang',
  'hintTitle':'title',
  'addIntroduce':'Add Introduce',
  'submitButton':'Submit',
  'comment':'comment',
};