final Map<String, String> zhCn = {
  'homeAppTitle':'小白部落格',
  'postedOn':'发布于',
  'language': '全球化',
  'scienceOnline':'科学上网',
  'home': '主页',
  'homeTitle':'关于我的主页',
  'homeSubTitle':'博客搭建',
  'homeIntroduce':'欢迎指教',
  'music':'音乐',
  'langZh' : '中文',
  'langEn' : 'ENGLISH',
  'nomalSea':'海',
  'nomalQiCai':'七彩',
  'gradientRotate':'动态旋转',
  'gradientSea':'动态海',
  'gradientQiCai':'动态七彩',
  'theme': '主题',
  'text':'字体',
  'cao':'草书',
  'xing':'行书',
  'kai':'楷书',
  'personName':'小白',
  'geocoor':'相距',
  'lat':'经度',
  'long':'纬度',
  'location':'地图',
  'rain':'雨',
  'sunny':'晴',
  'frontUntil':'距离周末还有',
  'backUntil':'天',
  'untilWeekend':'放假啦！',
  'mondayFeel':'每天都是新的开始',
  'tuesdayFeel':'喜欢就去坚持哦',
  'wednesdayFeel':'遗憾可能比失败更难熬',
  'thursdayFeel':'每天进步一点点',
  'fridayFeel':'当作最后一天',
  'weekendFeel':'努力也不要忘了生活',
  'article':'文章',
  'label':'标签',
  'personHome':'个人主页',
  'noLocation':'获取不到位置信息',
  'person':'个人',
  'flutter':'Flutter',
  'golang':'Go',
  'java':'Java',
  'personLabel':'个人中心',
  'flutterLabel':'flutter',
  'sciLabel':'科学上网',
  'javaLabel':'java',
  'goLabel':'golang',
  'hintTitle':'主题',
  'addIntroduce':'添加Introduce',
  'submitButton':'提交',
  'comment':'评论',
};